### ISSUE TITLE
Warningメッセージについて

### ISSUE THREAD

**Issue by ko31** [kuno1/ga-communicator#59]
- 使用バージョン：3.6.1

下記のような Warning メッセージが発生することがあるようです。

```
[02-Feb-2024 00:43:24 UTC] PHP Warning:  Attempt to read property "taxonomy" on null in /path/to/wp/wp-content/plugins/ga-communicator/vendor-prefixed/src/Kunoichi/GaCommunicator/Utility/PlaceHolders.php on line 52
```

該当箇所のソースを見ると以下のようになっていますが、`is_category()`、`is_tag()`、`is_tax()` それぞれの条件を満たすページへランダムにアクセスしても Warning が確認できませんでしたので、何か特定の条件でアクセスが行われないと発生しない模様です。

```
 51             if (is_category() || is_tag() || is_tax()) {
 52                 return get_queried_object()->taxonomy;
 53             } else {
 54                 return '';
 55             }
```

なお、プラグイン設定画面の「追加のスクリプト」「metaタグ」にて `taxonomy` のプレースホルダーは使用していない状態です。

**Comment by fumikito** [comment]
たぶん「試合結果」のような、「リーグは設定されているけど標準のWP_Queryではない機能を使っている」ページで発生しているかと思います。
`is_a` でチェックするようにします。
